services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ny_taxi"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8085:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      pgdatabase:
        condition: service_healthy

  taxi_ingest:
    image: taxi_ingest:v001
    depends_on:
      pgdatabase:
        condition: service_healthy
    command:
      [
        "--year=2021",
        "--month=1",
        "--pg_user=root",
        "--pg_pass=root",
        "--pg_host=pgdatabase",
        "--pg_port=5432",
        "--pg_db=ny_taxi",
        "--target_table=yellow_taxi_trips",
        "--chunksize=100000"
      ]
    restart: "no"

volumes:
  pgdata:
  pgadmin_data:
